-- liquibase formatted sql

-- changeset wladw:1758048566-64
CREATE TABLE npc
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    lvl             INTEGER,
    is_friendly     BOOLEAN,
    is_boss         BOOLEAN,
    spawn_chance    DOUBLE PRECISION,
    max_hp          DOUBLE PRECISION,
    max_mana        DOUBLE PRECISION,
    damage_min      DOUBLE PRECISION,
    damage_max      DOUBLE PRECISION,
    critical_chance DOUBLE PRECISION,
    critical_power  DOUBLE PRECISION,
    armor           DOUBLE PRECISION,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_npc PRIMARY KEY (id)
);

-- changeset wladw:1758048567-65
CREATE TABLE npc_dungeon_level
(
    dungeon_level_id BIGINT NOT NULL,
    npc_id           BIGINT NOT NULL
);

-- changeset wladw:1758048568-66
ALTER TABLE npc_dungeon_level
    ADD CONSTRAINT fk_npcdunlev_on_dungeon_level FOREIGN KEY (dungeon_level_id) REFERENCES dungeon_level (id);

-- changeset wladw:1758048569-67
ALTER TABLE npc_dungeon_level
    ADD CONSTRAINT fk_npcdunlev_on_npc FOREIGN KEY (npc_id) REFERENCES npc (id);

