-- liquibase formatted sql

-- changeset wladw:1758048555-50

CREATE TABLE dungeon
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_dungeon PRIMARY KEY (id)
);

-- changeset wladw:1758048556-51
CREATE TABLE dungeon_level
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lvl               INTEGER,
    recommended_power DOUBLE PRECISION,
    total_enemies_npc INTEGER,
    rating_points    DOUBLE PRECISION,
    dungeon_rounds    INTEGER,
    dungeon_id        BIGINT,
    dungeon_loot_id   BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_dungeon_level PRIMARY KEY (id)
);

-- changeset wladw:1758048557-52
CREATE TABLE dungeon_loot
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exp_reward    DOUBLE PRECISION,
    loot_table_id BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_dungeon_loot PRIMARY KEY (id)
);

-- changeset wladw:1758048558-53
CREATE TABLE dungeon_progress
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dungeon_id   BIGINT,
    character_id BIGINT,
    dungeon_level_id BIGINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_dungeon_progress PRIMARY KEY (id)
);

-- changeset wladw:1758048559-54
CREATE TABLE loot_table
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_loot_table PRIMARY KEY (id)
);

-- changeset wladw:1758048560-55
CREATE TABLE loot_table_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loot_table_id BIGINT,
    item_id       BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_loot_table_items PRIMARY KEY (id)
);

-- changeset wladw:1758048562-57
ALTER TABLE dungeon_level
    ADD CONSTRAINT FK_DUNGEON_LEVEL_ON_DUNGEON FOREIGN KEY (dungeon_id) REFERENCES dungeon (id);

-- changeset wladw:1758048563-58
ALTER TABLE dungeon_level
    ADD CONSTRAINT FK_DUNGEON_LEVEL_ON_DUNGEON_LOOT FOREIGN KEY (dungeon_loot_id) REFERENCES dungeon_loot (id);

-- changeset wladw:1758048564-59
ALTER TABLE dungeon_loot
    ADD CONSTRAINT FK_DUNGEON_LOOT_ON_LOOTTABLE FOREIGN KEY (loot_table_id) REFERENCES loot_table (id);

-- changeset wladw:1758048562-60
ALTER TABLE dungeon_progress
    ADD CONSTRAINT FK_DUNGEON_PROGRESS_ON_CHARACTER FOREIGN KEY (character_id) REFERENCES characters (id);

-- changeset wladw:1758048563-61
ALTER TABLE dungeon_progress
    ADD CONSTRAINT FK_DUNGEON_PROGRESS_ON_DUNGEON FOREIGN KEY (dungeon_id) REFERENCES dungeon (id);

-- changeset wladw:1758374812-623
ALTER TABLE dungeon_progress
    ADD CONSTRAINT FK_DUNGEON_PROGRESS_ON_DUNGEON_LEVEL FOREIGN KEY (dungeon_level_id) REFERENCES dungeon_level (id);

-- changeset wladw:1758048564-62
ALTER TABLE loot_table_items
    ADD CONSTRAINT FK_LOOT_TABLE_ITEMS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);

-- changeset wladw:1758048565-63
ALTER TABLE loot_table_items
    ADD CONSTRAINT FK_LOOT_TABLE_ITEMS_ON_LOOT_TABLE FOREIGN KEY (loot_table_id) REFERENCES loot_table (id);
