-- liquibase formatted sql

-- changeset wladw:1756925527343-1
CREATE TABLE character_classes
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255)                            NOT NULL,
    class_type           VARCHAR(50)                             NOT NULL,
    base_hp              DOUBLE PRECISION                        NOT NULL,
    base_strength        DOUBLE PRECISION                        NOT NULL,
    base_intellect       DOUBLE PRECISION                        NOT NULL,
    base_agility         DOUBLE PRECISION                        NOT NULL,
    base_critical_chance DOUBLE PRECISION                        NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_classes PRIMARY KEY (id)
);

-- changeset wladw:1756925527343-2
CREATE TABLE character_level_bonus
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level_number    INTEGER,
    total_points    DOUBLE PRECISION,
    bonus_hp        DOUBLE PRECISION,
    bonus_strength  DOUBLE PRECISION,
    bonus_intellect DOUBLE PRECISION,
    bonus_agility   DOUBLE PRECISION,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_level_bonus PRIMARY KEY (id)
);

-- changeset wladw:1756925527343-3
CREATE TABLE character_stats
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_hp              DOUBLE PRECISION                        NOT NULL,
    total_mana            DOUBLE PRECISION                        NOT NULL,
    total_strength        DOUBLE PRECISION                        NOT NULL,
    total_intellect       DOUBLE PRECISION                        NOT NULL,
    total_agility         DOUBLE PRECISION                        NOT NULL,
    total_critical_chance DOUBLE PRECISION                        NOT NULL,
    total_critical_power  DOUBLE PRECISION                        NOT NULL,
    total_gear_score      DOUBLE PRECISION                        NOT NULL,
    total_damage          DOUBLE PRECISION                        NOT NULL,
    total_armor           DOUBLE PRECISION                        NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_stats PRIMARY KEY (id)
);

-- changeset wladw:1756925527343-4
CREATE TABLE characters
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    character_level    INTEGER                                 NOT NULL,
    total_experience   DOUBLE PRECISION                        NOT NULL,
    is_bot             BOOLEAN                                 NOT NULL,
    user_id            BIGINT,
    character_class_id BIGINT,
    character_stat_id  BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_characters PRIMARY KEY (id)
);

-- changeset wladw:1756925527343-5
CREATE TABLE permissions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission_type VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    role_id         BIGINT,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

-- changeset wladw:1756925527343-6
CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    user_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

-- changeset wladw:1756925527343-7
CREATE TABLE role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset wladw:1756925527343-8
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    is_enabled BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset wladw:1756925527343-9
ALTER TABLE characters
    ADD CONSTRAINT uc_characters_character_stat UNIQUE (character_stat_id);

-- changeset wladw:1756925527343-10
ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

-- changeset wladw:1756925527343-11
ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

-- changeset wladw:1756925527343-12
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset wladw:1756925527343-13
ALTER TABLE users
    ADD CONSTRAINT uc_users_login UNIQUE (login);

-- changeset wladw:1756925527343-14
ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_CHARACTER_CLASS FOREIGN KEY (character_class_id) REFERENCES character_classes (id);

-- changeset wladw:1756925527343-15
ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_CHARACTER_STAT FOREIGN KEY (character_stat_id) REFERENCES character_stats (id);

-- changeset wladw:1756925527343-16
ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset wladw:1756925527343-17
ALTER TABLE permissions
    ADD CONSTRAINT FK_PERMISSIONS_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

-- changeset wladw:1756925527343-18
ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset wladw:1756925527343-19
ALTER TABLE role
    ADD CONSTRAINT FK_ROLE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

