-- liquibase formatted sql

-- changeset 1758048506:1
CREATE TABLE character_classes
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255)                            NOT NULL,
    class_type           VARCHAR(255)                            NOT NULL,
    base_hp              DOUBLE PRECISION                        NOT NULL,
    base_strength        DOUBLE PRECISION                        NOT NULL,
    base_intellect       DOUBLE PRECISION                        NOT NULL,
    base_agility         DOUBLE PRECISION                        NOT NULL,
    base_critical_chance DOUBLE PRECISION                        NOT NULL,
    main_stat            VARCHAR(255)                            NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_classes PRIMARY KEY (id)
);

-- changeset wladw:1758048507-2
CREATE TABLE character_equipment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    head_item_id      BIGINT,
    shoulders_item_id BIGINT,
    chest_item_id     BIGINT,
    hands_item_id     BIGINT,
    legs_item_id      BIGINT,
    feet_item_id      BIGINT,
    weapon_item_id    BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_equipment PRIMARY KEY (id)
);

-- changeset wladw:1758048508-3
CREATE TABLE character_inventory
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_inventory PRIMARY KEY (id)
);

-- changeset wladw:1758048509-4
CREATE TABLE character_level_bonus
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level_number    INTEGER,
    total_points    DOUBLE PRECISION,
    bonus_hp        DOUBLE PRECISION,
    bonus_strength  DOUBLE PRECISION,
    bonus_intellect DOUBLE PRECISION,
    bonus_agility   DOUBLE PRECISION,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_level_bonus PRIMARY KEY (id)
);

-- changeset wladw:1758048510-5
CREATE TABLE character_stats
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_hp              DOUBLE PRECISION                        NOT NULL,
    total_mana            DOUBLE PRECISION                        NOT NULL,
    total_strength        DOUBLE PRECISION                        NOT NULL,
    total_intellect       DOUBLE PRECISION                        NOT NULL,
    total_agility         DOUBLE PRECISION                        NOT NULL,
    total_critical_chance DOUBLE PRECISION                        NOT NULL,
    total_critical_power  DOUBLE PRECISION                        NOT NULL,
    total_gear_score      DOUBLE PRECISION                        NOT NULL,
    total_damage          DOUBLE PRECISION                        NOT NULL,
    total_armor           DOUBLE PRECISION                        NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_stats PRIMARY KEY (id)
);

-- changeset wladw:1758048511-6
CREATE TABLE characters
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255)                            NOT NULL,
    character_level        INTEGER                                 NOT NULL,
    total_experience       DOUBLE PRECISION                        NOT NULL,
    is_bot                 BOOLEAN                                 NOT NULL,
    user_id                BIGINT,
    character_class_id     BIGINT,
    character_stat_id      BIGINT,
    character_inventory_id BIGINT                                  NOT NULL,
    character_equipment_id BIGINT                                  NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_characters PRIMARY KEY (id)
);

-- changeset wladw:1758048512-7
CREATE TABLE inventory_item
(
    inventory_id BIGINT NOT NULL,
    item_id      BIGINT NOT NULL,
    CONSTRAINT pk_inventory_item PRIMARY KEY (inventory_id, item_id)
);

-- changeset wladw:1758048513-8
CREATE TABLE items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    type              VARCHAR(255)                            NOT NULL,
    slot_type         VARCHAR(255)                            NOT NULL,
    item_level        INTEGER                                 NOT NULL,
    quality           VARCHAR(255)                            NOT NULL,
    min_dungeon_level INTEGER                                 NOT NULL,
    stamina           DOUBLE PRECISION                        NOT NULL,
    strength          DOUBLE PRECISION                        NOT NULL,
    intellect         DOUBLE PRECISION                        NOT NULL,
    agility           DOUBLE PRECISION                        NOT NULL,
    critical_chance   DOUBLE PRECISION                        NOT NULL,
    critical_power    DOUBLE PRECISION                        NOT NULL,
    armor             DOUBLE PRECISION                        NOT NULL,
    is_available      BOOLEAN                                 NOT NULL,
    drop_chance       DOUBLE PRECISION                        NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

-- changeset wladw:1758048514-9
CREATE TABLE permissions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission_type VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    role_id         BIGINT,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

-- changeset wladw:1758048515-10
CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    user_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

-- changeset wladw:1758048516-11
CREATE TABLE role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset wladw:17580485017-12
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    is_enabled BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset wladw:1758048518-13
ALTER TABLE character_equipment
    ADD CONSTRAINT uc_character_equipment_chest_item UNIQUE (chest_item_id);

-- changeset wladw:1758048519-14
ALTER TABLE character_equipment
    ADD CONSTRAINT uc_character_equipment_feet_item UNIQUE (feet_item_id);

-- changeset wladw:1758048520-15
ALTER TABLE character_equipment
    ADD CONSTRAINT uc_character_equipment_hands_item UNIQUE (hands_item_id);

-- changeset wladw:1758048521-16
ALTER TABLE character_equipment
    ADD CONSTRAINT uc_character_equipment_head_item UNIQUE (head_item_id);

-- changeset wladw:1758048522-17
ALTER TABLE character_equipment
    ADD CONSTRAINT uc_character_equipment_legs_item UNIQUE (legs_item_id);

-- changeset wladw:1758048523-18
ALTER TABLE character_equipment
    ADD CONSTRAINT uc_character_equipment_shoulders_item UNIQUE (shoulders_item_id);

-- changeset wladw:1758048524-19
ALTER TABLE character_equipment
    ADD CONSTRAINT uc_character_equipment_weapon_item UNIQUE (weapon_item_id);

-- changeset wladw:1758048525-20
ALTER TABLE characters
    ADD CONSTRAINT uc_characters_character_equipment UNIQUE (character_equipment_id);

-- changeset wladw:1758048526-21
ALTER TABLE characters
    ADD CONSTRAINT uc_characters_character_inventory UNIQUE (character_inventory_id);

-- changeset wladw:1758048527-22
ALTER TABLE characters
    ADD CONSTRAINT uc_characters_character_stat UNIQUE (character_stat_id);

-- changeset wladw:1758048528-23
ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

-- changeset wladw:1758048529-24
ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

-- changeset wladw:1758048530-25
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset wladw:1758048531-26
ALTER TABLE users
    ADD CONSTRAINT uc_users_login UNIQUE (login);

-- changeset wladw:1758048532-27
ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_CHARACTER_CLASS FOREIGN KEY (character_class_id) REFERENCES character_classes (id);

-- changeset wladw:1758048533-28
ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_CHARACTER_EQUIPMENT FOREIGN KEY (character_equipment_id) REFERENCES character_equipment (id);

-- changeset wladw:1758048534-29
ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_CHARACTER_INVENTORY FOREIGN KEY (character_inventory_id) REFERENCES character_inventory (id);

-- changeset wladw:1758048535-30
ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_CHARACTER_STAT FOREIGN KEY (character_stat_id) REFERENCES character_stats (id);

-- changeset wladw:1758048536-31
ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset wladw:1758048537-32
ALTER TABLE character_equipment
    ADD CONSTRAINT FK_CHARACTER_EQUIPMENT_ON_CHEST_ITEM FOREIGN KEY (chest_item_id) REFERENCES items (id);

-- changeset wladw:1758048538-33
ALTER TABLE character_equipment
    ADD CONSTRAINT FK_CHARACTER_EQUIPMENT_ON_FEET_ITEM FOREIGN KEY (feet_item_id) REFERENCES items (id);

-- changeset wladw:1758048539-34
ALTER TABLE character_equipment
    ADD CONSTRAINT FK_CHARACTER_EQUIPMENT_ON_HANDS_ITEM FOREIGN KEY (hands_item_id) REFERENCES items (id);

-- changeset wladw:1758048540-35
ALTER TABLE character_equipment
    ADD CONSTRAINT FK_CHARACTER_EQUIPMENT_ON_HEAD_ITEM FOREIGN KEY (head_item_id) REFERENCES items (id);

-- changeset wladw:1758048541-36
ALTER TABLE character_equipment
    ADD CONSTRAINT FK_CHARACTER_EQUIPMENT_ON_LEGS_ITEM FOREIGN KEY (legs_item_id) REFERENCES items (id);

-- changeset wladw:1758048542-37
ALTER TABLE character_equipment
    ADD CONSTRAINT FK_CHARACTER_EQUIPMENT_ON_SHOULDERS_ITEM FOREIGN KEY (shoulders_item_id) REFERENCES items (id);

-- changeset wladw:1758048543-38
ALTER TABLE character_equipment
    ADD CONSTRAINT FK_CHARACTER_EQUIPMENT_ON_WEAPON_ITEM FOREIGN KEY (weapon_item_id) REFERENCES items (id);

-- changeset wladw:1758048544-39
ALTER TABLE permissions
    ADD CONSTRAINT FK_PERMISSIONS_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

-- changeset wladw:1758048545-40
ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset wladw:1758048546-41
ALTER TABLE role
    ADD CONSTRAINT FK_ROLE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset wladw:1758048547-42
ALTER TABLE inventory_item
    ADD CONSTRAINT fk_invite_on_character_inventory FOREIGN KEY (inventory_id) REFERENCES character_inventory (id);

-- changeset wladw:1758048548-43
ALTER TABLE inventory_item
    ADD CONSTRAINT fk_invite_on_item FOREIGN KEY (item_id) REFERENCES items (id);

